# Generated by Django 2.2.6 on 2021-01-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20210107_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Введите текст поста.<p>* Oбязательно для заполнения.</p>', verbose_name='Текст'),
        ),
    ]
