# Generated by Django 2.2.6 on 2021-01-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210112_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, help_text='Добавьте своё изображение', null=True, upload_to='posts/', verbose_name='Изображение'),
        ),
    ]
